### ISSUE TITLE
Bug: Rounding Issue

### ISSUE THREAD

**Issue by alec-horwitz** [learn-co-curriculum/programming_languages#5]
In the get_average_age_for_season function, the **sum of all contestant ages for season 10 is 644** and the **number of contestants is 25**. If you divide the sum of all ages in season 10 by the number of contestants, you end up with **25.76**. In Ruby, all integers are automatically rounded down. In order to fix this, you must enter it in the following way for it to pass all tests: 

_((sum of all ages)/ (number of contestants).to_f).round(0)_ 

None of these number operations were introduced anywhere in the pre-work leading up to this nor is this issue addressed in the lab!

**Comment by drakeltheryuujin** [comment]
Hi there,

Thank you for your feedback! We'll take this information into consideration in upcoming releases of this curriculum.

As always, thanks for contributing! 💙
